import Head from 'next/head'
import HomePage from '../components/HomePage'
import ProtectedRoute from '../components/ProtectedRoute'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Firebase Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <ProtectedRoute>
        <HomePage />
      </ProtectedRoute>

    </div>
  )
}
