import Head from 'next/head'
import HomePage from '../components/HomePage'
import { UserAuth } from '../context/AuthContext'
import { useRouter } from 'next/router'
import ProtectedRoute from '../components/ProtectedRoute'

export default function Home() {


  const { user } = UserAuth()
  const router = useRouter()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProtectedRoute>
        <HomePage />
      </ProtectedRoute>

    </div>
  )
}
